spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: search
          uri: http://www.google.com
          predicates:
            - Path=/search
            - After=2019-06-26T14:11:00.000-07:00[America/Denver]
        - id: search
          uri: http://www.yahoo.com
          predicates:
            - Path=/search
            - Before=2019-06-26T14:11:00.000-07:00[America/Denver]
        - id: demo
          uri: lb://demo-service
          predicates:
            - Path=/demo/**
          filters:
            - RewritePath=/demo/(?<segment>.*), /$\{segment}

